try to auto-test with GitHub action (#3)
* try to auto-test with GitHub action

diff --git a/.github/workflows/verilog_test.yml b/.github/workflows/verilog_test.yml
--- a/.github/workflows/verilog_test.yml
+++ b/.github/workflows/verilog_test.yml
@@ -22,15 +22,16 @@ jobs:
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
+      - uses: s-weigand/setup-conda@v1
       - name: Install Iverilog
         run: |
-          sudo apt-get install iverilog
+          conda install -c conda-forge iverilog
       - name: Run Test
         run: |
           cd spi_device
-          iverilog -l ./spi.v ./spi_tb.v-o spi.out
-# fails if no error message are present in the bench.
-          if grep -q "Error" ./spi_tb.v; then exit 1; fi
-          ./spi.out >> spi.res
-# fails if error message found in the simulation log.
-          if grep -q "Error" ./spi.res; then exit 1; fi
+          iverilog -l ./spi_device.v ./spi_device_tb.v -o spi_device.out
+          # fails if no error message are present in the bench.
+          if ! grep -q "failed" ./spi_device_tb.v; then exit 1; fi
+          ./spi_device.out >> spi_device.res
+          # fails if error message found in the simulation log.
+          if grep -q "failed" ./spi_device.res; then exit 1; fi
